### ISSUE TITLE
LongType field Droppping.

### ISSUE THREAD

**Issue by sumit-gupta-sgt** [JayLohokare/pySpark-flatten-dataframe#1]
Seems to be LongType field Dropping.

**Comment by JayLohokare** [comment]
@sumit-gupta-sgt
Can you add more details for this issue? I don't see why a particular data type will fail.

**Comment by sumit-gupta-sgt** [comment]
@JayLohokare  Parsing seems to be fine but strange, if i have single document its creating multiple json record in file.

`{
	"report": {
		"xx": {
			"abc": 1670,
			"a1": "O",
			"a2": 10,
			"a3": 28.120325,
			"a4": "mn",
			"a5": "O",
			"a6": 1453
		}
	}
}
`

**Comment by JayLohokare** [comment]
@sumit-gupta-sgt  Not sure why you are getting any errors. I have attached my output dataframe structure for your code.

<img width="756" alt="Screen Shot 2019-09-26 at 11 09 51 AM" src="https://user-images.githubusercontent.com/12843951/65705544-4ae36c00-e04e-11e9-995f-444dfffea4ce.png">
